#pragma once
#define M3D_CFG_BADATTRIBUTION 0x00
#define M3D_M3DS_BADMAINMODULE 0x01

#define M3D_MAX_SHADER_INFOLOG_LENGTH 4096
#define M3D_MAX_IFSTREAM_ERROR_LENGTH 1024
#define M3D_MAX_GAMECONSOLE_PYCMD_LENGTH 4096
#define M3D_MAX_GAMECONSOLE_VALUE_LENGTH 4096

#define M3D_MAX_BONE_COUNT 4

#define M3D_ASSET_TEXTURE 0
#define M3D_ASSET_MODEL 1
#define M3D_ASSET_SCENE 2
#define M3D_ASSET_UIFORM 3
#define M3D_ASSET_MATERIAL 4